### ISSUE TITLE
Add useEffect dependency on content

### ISSUE THREAD

**Issue by aidanwhiteley** [claytonmarinho/react-text-rotator#17]
Hi - great component - thanks.

When using the component with a static JS array for the content parameter, everything works as expected. All content elements from the array are displayed.

However, when the content is coming from a remote system (a fetch call to a CMS in my case), because the useEffect has no dependencies on content changes, the indexRef.current in next() always resolves to 0 if the content wasn't available on first render. This means that when the content is received from the remote system, only the first element in the array is still ever shown.

Adding , [content]) as the useEffect dependency in index.js means that the next() function "sees" the updated content on re-renders.

Hope the above makes sense as I'm only just starting to play with hooks and useEffect etc. However, the above change in a local copy works for me.

Of course, the problem doesn't occur if the ReactTextRotator is rendered after the fetch has completed which is probably the more "correct" usage.

**Comment by claytonmarinho** [comment]
Hi @aidanwhiteley 

Thanks for the message and sorry for the late response. I wanted to do some refactoring on this package and used the opportunity to add the dependency as you requested. Please try version 1.0.1 and let me know if is improved for you.

**Comment by aidanwhiteley** [comment]
Marvelous - looks good to me.
If interested, my use case included having an optional hyperlink in the content items JSON so I've created a new fork at https://github.com/aidanwhiteley/react-text-rotator which does just that.
Thanks again.

**Comment by claytonmarinho** [comment]
@aidanwhiteley I liked the idea, however, I created a new issue for that regard. Closing this one. Thanks.
