### ISSUE TITLE
Path Issue: Relating to Less Directory

### ISSUE THREAD

**Issue by Rythinx** [claytonmarinho/react-text-rotator#2]
There seems to be an issue with the path directory! 

I get the following error.

 Error: Cannot find module './styles/transitions.less'
W20180917-15:21:41.327(9)? (STDERR)     at Function.Module._resolveFilename (module.js:547:15)
W20180917-15:21:41.327(9)? (STDERR)     at Function.Module._load (module.js:474:25)
W20180917-15:21:41.327(9)? (STDERR)     at Module.require (module.js:596:17)
W20180917-15:21:41.327(9)? (STDERR)     at require (internal/module.js:11:18)
W20180917-15:21:41.327(9)? (STDERR)     at Object.<anonymous> (/Users/Peterbae/Desktop/DEV-PROJECTS/PORTFOLIO/peterbae/node_modules/react-text-rotator/lib/index.js:17:1)
W20180917-15:21:41.328(9)? (STDERR)     at Module._compile (module.js:652:30)
W20180917-15:21:41.328(9)? (STDERR)     at Object.Module._extensions..js (module.js:663:10)
W20180917-15:21:41.328(9)? (STDERR)     at Module.load (module.js:565:32)
W20180917-15:21:41.328(9)? (STDERR)     at tryModuleLoad (module.js:505:12)
W20180917-15:21:41.328(9)? (STDERR)     at Function.Module._load (module.js:497:3)
W20180917-15:21:41.329(9)? (STDERR)     at Module.require (module.js:596:17)
W20180917-15:21:41.329(9)? (STDERR)     at require (internal/module.js:11:18)
W20180917-15:21:41.329(9)? (STDERR)     at npmRequire (/Users/Peterbae/Desktop/DEV-PROJECTS/PORTFOLIO/peterbae/.meteor/local/build/programs/server/npm-require.js:133:10)
W20180917-15:21:41.329(9)? (STDERR)     at Module.useNode (packages/modules-runtime.js:650:18)
W20180917-15:21:41.329(9)? (STDERR)     at index.js (packages/modules.js:315:8)
W20180917-15:21:41.329(9)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180917-15:21:41.329(9)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180917-15:21:41.330(9)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180917-15:21:41.330(9)? (STDERR)     at main-homepage.js (imports/ui/pages/homepage/main-homepage.js:1:134)
W20180917-15:21:41.330(9)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180917-15:21:41.330(9)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180917-15:21:41.330(9)? (STDERR)     at require (packages/modules-runtime.js:244:21)

**Comment by claytonmarinho** [comment]
Hello @Rythinx.
Thanks for the report. Please try update to 0.0.5 and let me know if works fine for you.
Cheers.
