### ISSUE TITLE
Cannot import it in NextJS

### ISSUE THREAD

**Issue by DevDaksh** [claytonmarinho/react-text-rotator#26]
I am trying it import it in a nextjs project but cannot import it, error 

`Module not found: Can't resolve 'react'`

**Comment by claytonmarinho** [comment]
Hi @DevDaksh 

Tried a fresh nextjs install and worked fine. 

```
  "dependencies": {
    "next": "10.0.5",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-text-rotator": "^1.0.1"
  }
```
Which versions have currently?

**Comment by DevDaksh** [comment]
worked fine the next day when I restarted my dev server. Guess turning on and off works like a charm!
