### ISSUE TITLE
Remove react and react-dom from dependencies?

### ISSUE THREAD

**Issue by johnharris85** [claytonmarinho/react-text-rotator#32]
Hey, thanks for the library it's been super useful! 

I'm not a React / NPM expert by any means, but the specification of the above 2 packages as a dependency (in addition to a peer dependency) is causing issues with multiple React versions being installed. Are you open to a PR removing those and just leaving them as `peerDependencies` (which seems to be best practice for `react` & `react-dom` from my research)?

cc/ @imriven

**Comment by claytonmarinho** [comment]
@johnharris85 thanks for the feedback and sorry for the late response. 

Maybe it won't make sense for you anymore, but I did some changes recently including removing react and react-dom from dependencies. The new version is [1.2.0 ](https://github.com/claytonmarinho/react-text-rotator/releases/tag/v1.2.0). If you're interested please check it out.

Cheers.
