### ISSUE TITLE
Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by brentrobbins** [claytonmarinho/react-text-rotator#7]
I would like to use this with a gatsbyjs website, however after I leave the page with the rotator and go to another page I get this following warning:

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
```

Is there anyway to avoid this issue?

**Comment by claytonmarinho** [comment]
Hi @brentrobbins please consider trying the new version 0.0.6 which now is with React Hooks which may solve this problem. 
Cheers.

**Comment by claytonmarinho** [comment]
I'll close this issue. Case necessary, please re-open.

**Comment by brentrobbins** [comment]
Great! Thanks for letting me know @claytonmarinho I'll check it out.

**Comment by tobias-nest** [comment]
Hi @claytonmarinho, 
just fyi, the problem still occurs in version 0.0.6
